# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foodies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Auth'
pod 'Firebase/Core'

  # Pods for Foodies

  target 'FoodiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodiesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
